const fields = [
  "tumor_stage",
  "age_at_diagnosis",
  "days_to_birth",
  "gender",
  "disease",
  "primary_diagnosis_Acinar cell carcinoma",
  "primary_diagnosis_Adenocarcinoma with mixed subtypes",
  "primary_diagnosis_Adenocarcinoma, NOS",
  "primary_diagnosis_Bronchio-alveolar carcinoma, mucinous",
  "primary_diagnosis_Bronchiolo-alveolar adenocarcinoma, NOS",
  "primary_diagnosis_Bronchiolo-alveolar carcinoma, non-mucinous",
  "primary_diagnosis_Clear cell adenocarcinoma, NOS",
  "primary_diagnosis_Micropapillary carcinoma, NOS",
  "primary_diagnosis_Mucinous adenocarcinoma",
  "primary_diagnosis_Papillary adenocarcinoma, NOS",
  "primary_diagnosis_Signet ring cell carcinoma",
  "primary_diagnosis_Solid carcinoma, NOS",
  "morphology_8140/3",
  "morphology_8230/3",
  "morphology_8250/3",
  "morphology_8252/3",
  "morphology_8253/3",
  "morphology_8255/3",
  "morphology_8260/3",
  "morphology_8265/3",
  "morphology_8310/3",
  "morphology_8480/3",
  "morphology_8490/3",
  "morphology_8550/3",
  "site_of_resection_or_biopsy_Lower lobe, lung",
  "site_of_resection_or_biopsy_Lung, NOS",
  "site_of_resection_or_biopsy_Main bronchus",
  "site_of_resection_or_biopsy_Middle lobe, lung",
  "site_of_resection_or_biopsy_Overlapping lesion of lung",
  "site_of_resection_or_biopsy_Upper lobe, lung",
  "race_american indian or alaska native",
  "race_asian",
  "race_black or african american",
  "race_unknown",
  "race_white",
];

module.exports.fields = fields;
